### ISSUE TITLE
V109 DOF effect always on. Cannot be disabled 

### ISSUE THREAD

**Issue by chosendude** [Parallellines0451/GTAIV.ShaderFixesCollection#8]
Hi, im using game version 1.0.7.0 and after i installed V109 the DOF effect apparently broke. It's always on, and tuning on or off defenition setting only turns on/off motion blur. There is no difference in trying to change it using P key, or via menu.

**Comment by MagicAl6244225** [comment]
Depth of Field is now a separate setting on the Display Menu.

**Comment by chosendude** [comment]
![20230809005659_1](https://github.com/Parallellines0451/GTAIV.ShaderFixesCollection/assets/23643323/915b7050-80ce-43c2-9035-40008569f8e1)

No such setting in my menu

> Depth of Field is now a separate setting on the Display Menu.

**Comment by MagicAl6244225** [comment]
My apologies, It is, if you are using the shaders in conjunction with FusionFix. https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix

The change is intentional. You may revert to a different version of rage_postfx.fxc in your shaders folder to have the original functionality of the Definition setting. The amount of Depth of Field is set in timecyc.dat and if you replace pc/data/timecyc.dat with TBoGT/pc/data/timecyc.dat it will remove DoF from IV and TLAD as it does in TBoGT.

**Comment by chosendude** [comment]
I am  trying to figure out, how to make FusionFix working on the 1.0.7.0, because the "downgrade compatible version" 1.7.3 provided with ZolikaPatch IV somehow does not work.

In any case, thank you for the reply, will take this into account. Issue is resolved.
